# Generated by Django 4.1 on 2022-10-31 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0023_rename_id_product_category_category_id_and_more'),
        ('app_general', '0002_alter_delivery_note_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Order_to_Delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='code_product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_general.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_product.product'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Bank Transfer', 'Bank Transfer')], default='Cash On Delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('Unapprove', 'Unapprove'), ('Approve', 'Approve'), ('Banned', 'Banned')], default='Unapprove', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
