# Generated by Django 4.1 on 2022-11-02 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0023_rename_id_product_category_category_id_and_more'),
        ('app_general', '0003_remove_order_order_to_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='order_date',
            new_name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='address',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='quantity_product',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.customer'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.order'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Approve', 'Approve'), ('Banned', 'Banned')], default='Disapproved', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_product.product'),
        ),
    ]
