# Generated by Django 4.1 on 2022-11-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0007_contact_user_alter_contact_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='id',
            new_name='contact_id',
        ),
    ]
