# Generated by Django 4.1 on 2022-11-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0008_rename_id_contact_contact_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
