# Generated by Django 4.1 on 2022-11-02 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0010_remove_delivery_order_order_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_general.delivery'),
        ),
    ]
