# Generated by Django 4.1 on 2022-11-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0014_alter_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('customer', models.CharField(max_length=225)),
                ('product', models.CharField(max_length=225)),
                ('quantities', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
    ]
