# Generated by Django 4.1 on 2022-11-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0015_history_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History_Shop',
        ),
    ]
