# Generated by Django 4.1 on 2022-10-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_product_category_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('slug', models.SlugField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('special_price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('promotion_end', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('product_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_product.product_category')),
                ('product_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_product.product_type')),
            ],
        ),
    ]
