# Generated by Django 4.1 on 2022-10-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0005_newproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproduct',
            old_name='product_category_id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='newproduct',
            old_name='product_type_id',
            new_name='type_id',
        ),
    ]
