# Generated by Django 4.1 on 2022-10-29 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0006_rename_product_category_id_newproduct_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
            ],
        ),
        migrations.RenameField(
            model_name='newproduct',
            old_name='category_id',
            new_name='p_category',
        ),
        migrations.RenameField(
            model_name='newproduct',
            old_name='type_id',
            new_name='p_type',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.test'),
        ),
    ]
