# Generated by Django 4.1 on 2022-10-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0007_page_test_rename_category_id_newproduct_p_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='test',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='question',
            name='page',
            field=models.CharField(max_length=225),
        ),
    ]
