# Generated by Django 4.1 on 2022-10-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0011_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='newproduct',
            options={'verbose_name_plural': 'All Product'},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
