# Generated by Django 4.1 on 2022-10-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0012_remove_item_category_alter_newproduct_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproduct',
            old_name='p_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='newproduct',
            old_name='p_type',
            new_name='type',
        ),
    ]
