# Generated by Django 4.1 on 2022-10-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0013_rename_p_category_newproduct_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproduct',
            old_name='product_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='newproduct',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
