# Generated by Django 4.1 on 2022-10-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0014_rename_product_id_newproduct_id_newproduct_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproduct',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='image_product'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
