# Generated by Django 4.1 on 2022-10-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0015_newproduct_photo_alter_product_category_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_category',
            new_name='ProductCategory',
        ),
        migrations.RenameModel(
            old_name='Product_type',
            new_name='ProductType',
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
