# Generated by Django 4.1 on 2022-10-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0017_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='code_product',
        ),
    ]
