# Generated by Django 4.1 on 2022-10-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0018_rename_code_product_code_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Product_Category',
        ),
        migrations.RenameModel(
            old_name='ProductType',
            new_name='Product_Type',
        ),
    ]
