# Generated by Django 4.1 on 2022-10-30 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0019_rename_productcategory_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='product_id',
        ),
    ]
