# Generated by Django 4.1 on 2022-10-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0021_alter_product_code_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code_product',
            new_name='product_code',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
