# Generated by Django 4.1 on 2022-10-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0022_rename_code_product_product_product_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_category',
            old_name='id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='product_type',
            old_name='id',
            new_name='type_id',
        ),
    ]
